DEVIL_NAMES = [
    "A Disgraça",
    "O 25 De Março Na Véspera",
    "O Abre A Porta De Cueca",
    "O Abroba Aziática",
    "O Acarajé de Restaurante",
    "O Acepipe do Bolsonaro",
    "O Acorda Gato",
    "O Açúcar de Diplink",
    "O Agonia de Domingo",
    "O Água de Chuca Potável",
    "O Água De Danone",
    "O Água De Salsicha",
    "O Alergia no Brioco",
    "O Alma Gêmea",
    "O Alvo de Coronga",
    "O Amigo Secreto",
    "O Anarco Capitalista",
    "O Anarco-Conservador",
    "O Anarcofaptalista",
    "O Anjo caído",
    "O Anúncio da Jequiti",
    "O Anúncio de Aumente seu Pênis",
    "O Aponta O Salgado E Pergunta Qual O Sabor Dele",
    "O Aquele Que A Jujuba Não Gruda No Céu Da Boca",
    "O Aquele que Desvia",
    "O Arco-Íris Da Noite",
    "O Armengado",
    "O Arnica Na Queimadura",
    "O Arquiduque do Puteiro do Cabrunco",
    "O Arranca Canto de Unha",
    "O Arroto de Fanta Laranja ",
    "O Arroz Com Passas",
    "O Asmodeus",
    "O Assento Do Meio",
    "O Assobio Da Samsung",
    "O Assovio No Banheiro",
    "O Assusta Gato",
    "O Astrólogo Terraplanista",
    "O Ateu Antivacina",
    "O Atualização Do Java",
    "O Azazel",
    "O Azélélé",
    "O Azêmola",
    "O azia na madrugada ",
    "O Azuado",
    "O Baba de Coronga",
    "O Baby Talk Do Inferno",
    "O Bacanal da Louça Suja",
    "O Baidu",
    "O Balão Trágico",
    "O Bananinha",
    "O Banda Pop Que Faz Comercial De Fanta",
    "O Banhado A Ouro",
    "O Banheira do Gugu",
    "O Banho De Fanta",
    "O Banho Dourado",
    "O Banshee da Menopausa",
    "O Baphomet",
    "O Barata Com Asa",
    "O Barata que Voa",
    "O Baratão do MIB",
    "O Barba Rala",
    "O Barriga de Grávida de Taubaté",
    "O Batata Show",
    "O Bate Coração",
    "O Bate-papo do UOL",
    "O Bayblade de Cocô",
    "O Bebe Água de Chuca",
    "O Bebê Macabro",
    "O Beija de Olho Aberto",
    "O Bel do Chiclete",
    "O Belzeboss E Sua Banda",
    "O Belzebu",
    "O Berne de Coca",
    "O Besta Fera",
    "O Beto Gambiarra",
    "O Beto Jamaica",
    "O Bicho Papão",
    "O Bicho Piruleta",
    "O Bicicleta de Bambu",
    "O Bico De Corvo No Lugar Dos Olhos",
    "O Bigode Sujo",
    "O Binga Mucha",
    "O BIOS da Positivo",
    "O Birolittle",
    "O Biscoito ou Bolacha",
    "O Bode Com Três Patas",
    "O Boi Do Cu Branco",
    "O Boleto Bancário",
    "O Bolo de Batata",
    "O Bolo de São Paulo",
    "O Bolsolambebolista",
    "O Bolsonaro de Casco",
    "O Bolsonaro de Cenoura",
    "O Bolsonaro Xerecudo",
    "O Bom Dia de Elevador",
    "O Bombado Que Geme",
    "O bombeiro de hospital ",
    "O Borracheiro Fechado",
    "O Botão Russo Pra Download",
    "O Briga De Galo",
    "O Brinquedo Sem Pilha",
    "O Brioco Coçante",
    "O Brota no Cultão",
    "O Bug de Hello World",
    "O Bungee Jump Wireless",
    "O Cabeça De Grulha",
    "O Cabeça de Morcego",
    "O Cabelo no Ralo",
    "O Cabrunco",
    "O Cachorro Vegano",
    "O Cadreel",
    "O Caduzinho Do 8º",
    "O Caga no Chuveiro",
    "O Caganito De Coelho",
    "O Caimbra Dormindo",
    "O Calota De Fusca",
    "O Cancela Uber",
    "O Câncer de Cu",
    "O Canclomo do Broxonaro",
    "O Caniggia",
    "O Canta Junto",
    "O Canta Legião",
    "O Cão",
    "O Capa De Gordura",
    "O Capa Preta",
    "O Capa Verde",
    "O Capacho de Fascista",
    "O Capeta",
    "O Capetão de Chinelo",
    "O Capiroto",
    "O Cara Branca",
    "O Cara Que Arranha Um Violão E Comprou Um Ukulele",
    "O Cara Que Fuma No Carro Compartilhado",
    "O Carbúnculo",
    "O Carbúnculo",
    "O Cardume suicida ",
    "O Carnaval Em Curitiba",
    "O Carnaval Fora De Época",
    "O Carnê do IPTU",
    "O Carne E Unha",
    "O Cartão do Santander",
    "O Cartucho Fotográfico",
    "O Catchup na Pizza",
    "O Cefaléia de Glande",
    "O Chama Elevador No 1º Andar",
    "O Chama Formiga",
    "O Chama Porteiro",
    "O Chapéu De Couro",
    "O Chapolin Sincero",
    "O Chassi de Grilo",
    "O Cheiro de Espirro",
    "O Chernobyl de Ebola",
    "O Chifre Pequeno",
    "O Chifre Rosa",
    "O Chifrudo",
    "O Chifrudo de Chorume",
    "O Chinelo Emborcado",
    "O Chocolate Sensação Duro",
    "O Chupa Cu Presidencial",
    "O Chupacu de Goianinga",
    "O Churrasco de Mau Agouro",
    "O Churrasco Vegano",
    "O Chuta Retrovisor",
    "O Chuva Bem Na Hora",
    "O Cigarro de Amianto",
    "O Cílio de Pentelho",
    "O Cinzeiro Com Água",
    "O Coach de Cacarejo",
    "O Coisa Ruim",
    "O colchão mal-amarrado ",
    "O Colherada Na Marmita",
    "O Come Cu de Quem tá Lendo",
    "O Comercial De Site De Hotel",
    "O Comida De Avião",
    "O Compra Cachorro",
    "O Compra Corote com Dinheiro de Criança",
    "O Condição Sine Qua Non",
    "O Confere O Óleo",
    "O Conje de Maringá ",
    "O Conversa Sobre O Clima",
    "O Conversa Sobre Política",
    "O Convida O Padre",
    "O Coringa do Letto",
    "O Corno de Biqueira",
    "O Coronga",
    "O Corongado de Chorume",
    "O Corote Azul",
    "O Corte Abrupto Em Esqueceram De Mim",
    "O Corte Com Papel",
    "O Cortininha De Plástico",
    "O Cotonete Genérico",
    "O Cover Do Roupa Nova",
    "O Cramunhão",
    "O Crédito Rotativo",
    "O Crepe de Bosta Seca",
    "O Crítica Da Razão Pura",
    "O Dá Sabonete",
    "O Dá Skip No Anúncio",
    "O Dá Spoiler",
    "O Dança na Privada",
    "O Darkness, my old friend",
    "O Defende Racista",
    "O Dentista 24 Horas",
    "O Dentista Novato",
    "O Deputado Plagiador",
    "O Derrotado",
    "O Derruba Arnaldo",
    "O Descasca Banana com Faca",
    "O Descasca Calcanhar",
    "O Deseja Receber Notificações",
    "O Desgracento",
    "O Desvia Verba",
    "O Deus Da Mesopotâmia",
    "O Deus Lagarto",
    "O Diabrete",
    "O Dilma da Havan",
    "O Dipirona Rançosa",
    "O Diretor da Escolinha do Papai do Chão",
    "O Dirige Bêbado",
    "O Dirige Sem Carteira",
    "O Discurso Epistemológico",
    "O Dissimulado",
    "O Ditador",
    "O Divertido do Velório",
    "O Divisão por Zero",
    "O Dona Rosalva Engana Velho",
    "O Dragão",
    "O E As Namoradinhas?",
    "O É o Tchan",
    "O Eclipse Parcial",
    "O Ejaculador Inútil",
    "O Embrulho Molenga",
    "O Emoticon Safado",
    "O Encardido",
    "O Encarquilhado",
    "O Enroladinho de Fimose",
    "O Entropia da Imersão",
    "O Equação de Segundo Grau",
    "O Escolhe Feijão",
    "O Escoteiro de Apartamento",
    "O Escuma de Chorume",
    "O Espírito de Porco",
    "O Espirra Menstruada",
    "O Espirro De Grilo",
    "O Espirro Reverso",
    "O Estapeável",
    "O Estraga Suruba",
    "O Estrupador de Capacete",
    "O Esvazia Piscina",
    "O ET de Varginha",
    "O Explica Piada",
    "O Extrapola Orçamento",
    "O Fã de Banco",
    "O Faca Guinsu Cega",
    "O Fala Dormindo",
    "O Fala Imbigo",
    "O Falta Hemodiálise",
    "O Família Alemã",
    "O Fanta Com Cerveja",
    "O Fanta Diet",
    "O Fanta Sem Gás",
    "O Farofa Doce",
    "O Farofa Molhada",
    "O Fatia Grosso",
    "O Faxineiro do Hades",
    "O Faz Compilação",
    "O Faz Favor",
    "O Febre Do Rato",
    "O Fede a 17",
    "O Feijão no Pote de Sorvete",
    "O Fiapo De Manga No Aparelho",
    "O Figurante de Podcast",
    "O Fila da Lotérica",
    "O Fila do Bom-Prato",
    "O Filho Do Melado Molhado",
    "O Financiamento",
    "O First",
    "O Flor De Jorge Tadeu",
    "O fogo na Babilônia",
    "O Formata Meu PC",
    "O Frango Ou Pasta",
    "O Fratura de Pênis",
    "O Fratura Espontânea",
    "O Fungo na Panela",
    "O Fura Linguiça",
    "O Furta Cebolas",
    "O Furúnculo de Fimose",
    "O Furunfada na Sangria",
    "O Furunfada Pecaminosa",
    "O Garantia Estendida",
    "O Gasolina Azul",
    "O Gato de Almofada",
    "O Gato Mia",
    "O Gelo E Limão",
    "O Gelol na Glande",
    "O Gelol no Zói",
    "O Gemidão Do Zap",
    "O Genro",
    "O Gerente Guimarães",
    "O Gilmar Mendes",
    "O Girabenga",
    "O Glande Peluda",
    "O Glande Rachada",
    "O Godzilla Giroflex ",
    "O Goleiro-Linha",
    "O Grade Na Chaminé",
    "O Grande Arrombado",
    "O Grande Vermelho",
    "O Guarda-Chuvinha De Chocolate",
    "O Guardanapo de Ânus",
    "O Guardião 30 Horas",
    "O Guaxinim De Miami",
    "O Halloween De Apartamento",
    "O Hannibal Lecter Vegano",
    "O Harpa Paraguaia",
    "O He-Man Branquelo",
    "O Hemograma Completo",
    "O Hétero Não Praticante",
    "O Hinode ",
    "O História Repetida",
    "O Homem do Saco",
    "O Homofóbico",
    "O Ifrit",
    "O Imundiçado",
    "O Imundo",
    "O Incel Mingaleiro",
    "O Índice MR",
    "O Infecção Hospitalar",
    "O Inimigo",
    "O Inimigo Do Gerente",
    "O Inseto No Ouvido",
    "O Inventor Do Java",
    "O Já fiz o dever, professora",
    "O Jacaré de Enchente",
    "O Jacaré de Virilha",
    "O jamanta estrondosa",
    "O Janela Do Skype",
    "O Java",
    "O Jesus do SBT",
    "O Jornalista Antivacina",
    "O Jura Pela Mãe",
    "O Juros Do Cartão",
    "O Kevin Dos Backstreet Boys",
    "O Kiba Twitter",
    "O Kit Da Avon",
    "O Lá Ela",
    "O Lança Pedrisco",
    "O Lasanha De Frango",
    "O Lei Ruanê",
    "O Lembrancinha",
    "O Leva Amigo",
    "O Leva Casaquinho",
    "O Ligação de São Paulo",
    "O Limpa Trilho",
    "O Linguiça de Dejeto",
    "O Linguiça De Rena",
    "O Link Quebrado",
    "O Lombra da Maconha",
    "O Louça Suja Seca",
    "O Lucifer",
    "O Luisa Mell Contra Schrodinger",
    "O Lupa Na Formiga",
    "O Macaco De Asa",
    "O Macaco Voadouro",
    "O Macarrão Quebrado",
    "O Macho Camarote",
    "O Macrohard Onfire ",
    "O Madeirite Molhada",
    "O Malamanhado",
    "O Maldito",
    "O Malégno",
    "O Malígno",
    "O Malte 90",
    "O Malvadão",
    "O Manda Áudio",
    "O Manhoso",
    "O Manteiga Rançosa",
    "O Maradona",
    "O Marco Feliciano",
    "O Margarina Amarelada",
    "O Margarina Na Maçaneta",
    "O Marmita Vegana",
    "O Marreco de Maringá",
    "O Marta Golpista de Uberlândia",
    "O Marvi Talarica",
    "O Marxista Conservador",
    "O Mascu do Mingau",
    "O Mastema",
    "O Mau Encarnado",
    "O Maurício Mattar",
    "O Mazelento",
    "O Médico Sem Luva",
    "O Mefisto",
    "O Mefistófeles",
    "O Megazord de Disgraça",
    "O Meias Vivarina Furada",
    "O Mel C. Das Spice Girls",
    "O Mel No Presunto",
    "O Meu Pagamento Que Não Chega",
    "O Mexe no Meu Prato",
    "O Microondas de Empresa",
    "O Millenial",
    "O Mimeógrafo de Fala",
    "O Miníocre",
    "O Mitocôndria de Glúten",
    "O Mochila de Criança",
    "O Mochila de Criança de Jequié",
    "O Mocinho Ali De Baixo",
    "O Mocorongo",
    "O Mocotó Vegano",
    "O Moderador do mIRC",
    "O Moleskine",
    "O Mônica de Biscuit",
    "O Moonwalker de Curupira",
    "O Morde Língua",
    "O Motoboy de Treta",
    "O Motor de Girabenga",
    "O Mun-ha",
    "O Música Alta no Busão",
    "O Música Do Fantástico",
    "O Não Emenda",
    "O Nariz Entupido De Um Lado Só",
    "O Nazgul do Harry Potter",
    "O Nazista de Sapatênis",
    "O Nem Convida Pro Réveillon",
    "O Nem Todo Cristão",
    "O Nibiru de Calango",
    "O Nissan Batido",
    "O Noel Magro",
    "O Noite Infeliz",
    "O Nojentamente Sensual",
    "O Nosferatu",
    "O Noz Mole",
    "O Noz Podre",
    "O numero que liga no celular e desliga sem falar nada",
    "O Obrigada Double U",
    "O Oficial De Justiça",
    "O Oh Oh do ICQ",
    "O Olho de Cobra",
    "O Oração Subordinada Completiva Do Inferno",
    "O Ortobom na Cueca",
    "O Ósculo no Boga",
    "O Padrão Da Tomada",
    "O Padre de Twitter",
    "O Paga Meia",
    "O Pai da Mentira",
    "O Palpatine de Fraldão",
    "O Pão Amassado",
    "O Pão Seco",
    "O Papai Do Chão",
    "O Papai Noel De Agosto",
    "O Papai Noel De Regata",
    "O Papai Noel Magrelo",
    "O Papelão Molhado",
    "O Parabéns Ao Contrário",
    "O Parede Mijada",
    "O Passa Minâncora",
    "O Passa Roupa no Corpo",
    "O Passo Largo",
    "O Pastilha Valda Sem Açúcar",
    "O Pau Bosta",
    "O Pazuzu da Ragatanga",
    "O Pé de Bode",
    "O Pé De Cobra",
    "O Pé De Gancho",
    "O Pé De Moça",
    "O Pé De Ovelha",
    "O Pé Preto",
    "O Pé Sujo",
    "O Pedra De Bingo",
    "O Pega-Coxa",
    "O Pelada",
    "O Pelé Calado",
    "O Pele De Milho Na Gengiva",
    "O Pele Vermelha Do Cão",
    "O Pelinha De Unha",
    "O Pênis Ardido",
    "O Pergunta No Final Da Aula",
    "O Peru Ressecado",
    "O Piada Do Peru",
    "O Picolé de Margarina",
    "O Pinha Pintada",
    "O Pipoca Murcha",
    "O Plano de Saúde",
    "O Plastiquinho Do CD Novo",
    "O Poema do Gato",
    "O Ponto do Marido",
    "O Precisamos Conversar",
    "O Pregador de Busão",
    "O Pregueteiro",
    "O Presente Só De Manhã",
    "O Presépio De Biscuit",
    "O Presidente Corongado",
    "O Presidente Temer",
    "O Professor de Matemática",
    "O Programa Do Imposto De Renda",
    "O Prolapso Retal",
    "O Pudim Com Ameixa",
    "O Purê no Hotdog",
    "O Quântico",
    "O Quebra-Molas Quadrado",
    "O Quebra-Taça",
    "O Queijo Mofado",
    "O Quer Que Embrulha?",
    "O Quina De Mesa",
    "O Quiosque Hypado",
    "O Rabanete Do Asfalto",
    "O Rabo-de-Seta",
    "O Rabudo",
    "O Rasta Bananeira",
    "O Rela Nitu",
    "O Renderiza Maldade",
    "O Repórter Do Datena",
    "O Repórter Na Chuva",
    "O Restinho De Comida Molhado No Ralo",
    "O Reunião Com Advogado",
    "O Ringtone",
    "O Robô do Telemarketing",
    "O Rodo De Plástico",
    "O Ronald McDonald",
    "O Ronca e Peida",
    "O Rouba No Bingo",
    "O Roupa Branca",
    "O Rum Sabor Maçã Verde",
    "O Sabão Azul Ressecado",
    "O Sabonete Fino",
    "O Sabonete Peludo",
    "O Sachê de Azia",
    "O Sacola Paga",
    "O Sagu De Sobremesa",
    "O Sai Fanta Pelo Nariz",
    "O Saleiro da Morte",
    "O Samambaia Alcoólatra",
    "O Sarnento",
    "O Satã",
    "O Satanás",
    "O Schopenhauer",
    "O Segurança do Extra",
    "O Sem Teto Gelado",
    "O Sem Teto Geraldo",
    "O Semblante de Belzebu",
    "O Sêmen Ungido",
    "O Senha Inválida",
    "O Senta Com Pratinho No Colo",
    "O Serviço De Proteção Ao Crédito",
    "O Sete Estrelas",
    "O Sete Pele",
    "O Sete Peles",
    "O Sete Peles Falsas",
    "O Seu Mé",
    "O Shorts De Nylon",
    "O Sier",
    "O Silas Malafaia",
    "O Silmar Geladinho",
    "O Simeris",
    "O Simulador de Úlcera",
    "O Sinteco Gelado",
    "O Skype",
    "O Smilinguido",
    "O Só Lê O Título E Já Vai Comentar",
    "O Só Mais Um",
    "O Sopa de Verão",
    "O Sr. Los Angeles",
    "O Sub-Reptício",
    "O Suco de Sangue",
    "O Suflair Esbranquiçado",
    "O Sujeira De Umbigo",
    "O Supremo Chanceler da Disgraça",
    "O Surra de Pau Mole ",
    "O Surubão de Noronha ",
    "O Sushi De Queijo",
    "O Taça De Plástico",
    "O Tang De Uva Na Garrafa Pet",
    "O Tapa-Tomada",
    "O Tapete de Chewbacca",
    "O Tapete Molhado",
    "O Tardígrado Vitimista",
    "O Te Convida Pro Réveillon",
    "O Tela Azul da Morte",
    "O Tem Na Netflix",
    "O Teste de Turingue ",
    "O Tim Recados",
    "O Tinder Fake Do Sexo Oposto",
    "O Tinhaco",
    "O Tinhoso",
    "O Tinhoso do Tinder",
    "O Tinta de Parede",
    "O Tinta Fresca",
    "O Tio Do Caixão",
    "O Tio do Churrasco",
    "O Tio Do Pavê",
    "O Titiu Luci",
    "O Toma Fanta",
    "O Tompero de Miojo",
    "O Topada no Móvel",
    "O Tranca Rua",
    "O Transformer Comestível",
    "O Trem Da Agonia",
    "O Treme Tela do MSN",
    "O Três Dentes",
    "O Três Volantes",
    "O Tridente De Plástico",
    "O Trismegisto",
    "O Tristonho da Suruba ",
    "O Tuíte com Nota de Rodapé",
    "O Turma da Imbonha",
    "O Tutu De Guaianazes",
    "O Uh Lalá",
    "O Úlcera Varicosa ",
    "O Último Botão Do Colarinho",
    "O Uncle Jack",
    "O Vale CD No Amigo Secreto",
    "O Vassoura De Bruxa",
    "O Vaza Fralda",
    "O Ventilador de teto",
    "O Ventilador Empoeirado",
    "O Verificação De Disco",
    "O Versão Pagode De Noite Feliz",
    "O Vinho Enlatado",
    "O Viquingue Sulistão",
    "O Virose Bacteriana",
    "O Vírus do Ipiranga",
    "O Vizinho Alegrão",
    "O Vocalista De Metal",
    "O Voldemort de Sucupira",
    "O Vota 17",
    "O WhatsApp da Hemorroida ",
    "O Wi-Fi De Hospital",
    "O Xibiu Coçado",
    "O Xinga no Twitter",
    "O Ziper no Saco",
    "O Zoinho Virado",
    "O Mickey Mouse do Governo",
    "O Limpa Raba De Pé",
    "O Foge da Quarentena",
    "O Exame Positivo pra Coronga",
    "O Cloroquina de Nióbio",
    "O Advogado do Coronga",
    "O Capitão Corona",
    "O Bolsonero",
    "O Bafo de Coronga",
    "O Nega Ciência",
    "O Paumandetta",
    "O Furunfada de Coronga",
    "O Carniça Letárgica",
    "O Moisés do Silvio Santos",
    "O Cruzado",
    "O Lambe Maçaneta",
    "O Peida na Farofa",
    "O Caminhão Cata Veio",
    "O Consciência Cauterizada",
    "O Pregador de Prosperidade",
    "O Aparição das Quintas Feiras",
    "Esfaqueado que não sangra",
    "O Fala Extrema Imprensa",
    "O Ungido no Chorume",
    "O Caixa de Areia de Gato",
    "O Jumento Corongado",
    "O Cowvid 17",
    "O Xereca Esfolada",
    "O Pente de Xibiu",
    "O L023",
    "O Cachorro Quente de Pão de Milho",
    "O Macho Planilhinha",
    "O CEO de MEI",
    "O Cunhado que Pede Dinheiro",
    "O Boronga",
    "O Bolsoronga",
    "O 04 do Condomínio",
    "O Digital Influenza",
    "O Corta Máscara",
    "O PowerPoint Analógico",
    "O Abraço de Coronga",
    "O Furunfada de Coronga",
    "O Homem de Bem",
    "O Vibrião Colérico",
    "O Endoscopia Reversa",
    "O Colonoscopia com Câmera de Ombro",
    "O Berimbal Wireless",
    "O Tuberculose Multirresistente",
    "O Coronga de Academia",
    "O Marombeiro Corongado",
    "O Comorbidade",
    "O Alter Ego do Excremento",
    "O Garantista de Ocasião",
    "O Punk Conservador",
    "O Xerografado com Acetona",
    "O Vereador Federal",
    "O Café de Água de Salcicha",
    "O Segway do Barranco",
    "O Infecção Nosocomial",
    "O Infecção Hospitalar",
    "O Música do Cachorrinho Fiadaputa",
    "O Efeito Ernesto",
    "O Mascarar de Asvenal",
    "O Sabonete de Chorume"
]